export const FEED_ADD = 'FEED_ADD';
export const FEED_REMOVE = 'FEED_REMOVE';
export const STORY_MARK_AS_READ = 'STORY_MARK_AS_READ';
export const STORIES_ADD = 'STORIES_ADD'; 
export const STORIES_REMOVE = 'STORIES_REMOVE';
export const FAVORITE_STORY_ADD = 'FAVORITE_STORY_ADD'; 
export const FAVORITE_STORY_REMOVE = 'FAVORITE_STORY_REMOVE'; 